# Generated by Django 4.0.2 on 2022-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommend', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
